/**
 * LUMINARK Inner Child Journal - Export Functionality
 * Exports journal entries to CSV and PDF formats
 */

import * as FileSystem from "expo-file-system";
import * as Sharing from "expo-sharing";
import * as Print from "expo-print";
import type { JournalEntry } from "./storage";

/**
 * Escape a value for CSV format
 */
function escapeCsv(value: any): string {
  const str = String(value ?? "");
  if (/[",\n\r]/.test(str)) {
    return `"${str.replace(/"/g, '""')}"`;
  }
  return str;
}

/**
 * Convert journal entries to CSV string
 */
export function journalToCsv(entries: JournalEntry[]): string {
  const headers = ["id", "created_at", "title", "tags", "content"];
  const lines = [headers.join(",")];

  for (const entry of entries) {
    lines.push(
      [
        escapeCsv(entry.id),
        escapeCsv(entry.created_at),
        escapeCsv(entry.title),
        escapeCsv((entry.tags || []).join("|")),
        escapeCsv(entry.content),
      ].join(",")
    );
  }

  return lines.join("\n");
}

/**
 * Share journal as CSV file
 */
export async function shareJournalCsv(entries: JournalEntry[]): Promise<void> {
  const csv = journalToCsv(entries);
  const timestamp = new Date().toISOString().split("T")[0];
  const filename = `luminark_journal_${timestamp}.csv`;
  const path = `${FileSystem.cacheDirectory}${filename}`;

  await FileSystem.writeAsStringAsync(path, csv, {
    encoding: FileSystem.EncodingType.UTF8,
  });

  await Sharing.shareAsync(path, {
    mimeType: "text/csv",
    dialogTitle: "Share Journal CSV",
  });
}

/**
 * Escape HTML special characters
 */
function htmlEscape(str: string): string {
  return (str || "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}

/**
 * Generate HTML for PDF export
 */
function generateJournalHtml(entries: JournalEntry[]): string {
  const rows = entries
    .slice()
    .reverse()
    .map(
      (entry) => `
      <div class="entry">
        <div class="entry-title">${htmlEscape(entry.title)}</div>
        <div class="entry-meta">
          ${htmlEscape(entry.created_at)} &middot; ${htmlEscape((entry.tags || []).join(", ") || "no tags")}
        </div>
        <div class="entry-content">${htmlEscape(entry.content)}</div>
      </div>
    `
    )
    .join("");

  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <style>
    * { box-sizing: border-box; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Arial, sans-serif;
      padding: 24px;
      color: #1a1a1a;
      line-height: 1.5;
    }
    .header {
      border-bottom: 2px solid #00ff41;
      padding-bottom: 16px;
      margin-bottom: 24px;
    }
    h1 {
      margin: 0 0 8px;
      color: #0a0a0a;
      font-size: 28px;
    }
    .subtitle {
      color: #666;
      font-size: 14px;
    }
    .entry {
      padding: 16px;
      border: 1px solid #ddd;
      border-radius: 12px;
      margin-bottom: 16px;
      background: #fafafa;
    }
    .entry-title {
      font-weight: 700;
      font-size: 18px;
      color: #0a0a0a;
    }
    .entry-meta {
      color: #666;
      font-size: 12px;
      margin: 6px 0 12px;
    }
    .entry-content {
      white-space: pre-wrap;
      line-height: 1.6;
      color: #333;
    }
    .footer {
      margin-top: 32px;
      padding-top: 16px;
      border-top: 1px solid #ddd;
      font-size: 12px;
      color: #999;
      text-align: center;
    }
  </style>
</head>
<body>
  <div class="header">
    <h1>Inner Child Integration Journal</h1>
    <div class="subtitle">LUMINARK Framework &middot; Exported ${new Date().toLocaleDateString()}</div>
  </div>
  ${rows || "<p>No journal entries.</p>"}
  <div class="footer">
    Generated by LUMINARK &middot; luminark.io
  </div>
</body>
</html>`;
}

/**
 * Share journal as PDF file
 */
export async function shareJournalPdf(entries: JournalEntry[]): Promise<void> {
  const html = generateJournalHtml(entries);
  const { uri } = await Print.printToFileAsync({ html });

  await Sharing.shareAsync(uri, {
    mimeType: "application/pdf",
    dialogTitle: "Share Journal PDF",
  });
}

/**
 * Check if sharing is available on this device
 */
export async function isSharingAvailable(): Promise<boolean> {
  return await Sharing.isAvailableAsync();
}
